SELECT TO_CHAR(SYSDATE,'HH12:MI:SS') AS CURRENTTIME FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY') AS TODAY FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY MONTH YYYY') AS TODAY FROM DUAL;
SELECT TO_CHAR(SYSDATE) AS TODAY FROM DUAL;
SELECT TO_CHAR(SYSDATE,'AM') AS TODAY FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'FRIDAY') AS NEXTFRIDAY FROM DUAL;
SELECT TRUNC(SYSDATE,'MONTH') AS NEXTMONTH FROM DUAL;
SELECT TRUNC(SYSDATE,'YEAR') AS NEXTYEAR FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY';
CREATE TABLE EMP(ENO NUMBER,NAME VARCHAR(20),JOINING DATE);

INSERT INTO EMP VALUES(1, 'AAAA', TO_DATE('01-01-2000', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(2, 'BBBB', TO_DATE('01-02-2001', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(3, 'CCCC', TO_DATE('02-03-2002', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(4, 'DDDD', TO_DATE('07-04-2003', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(5, 'EEEE', TO_DATE('14-04-2003', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(6, 'FFFF', TO_DATE('03-03-2024', 'DD-MM-YYYY'));
INSERT INTO EMP VALUES(7, 'GGGG', TO_DATE('05-03-2024', 'DD-MM-YYYY'));

SELECT ENO,NAME,JOINING,TO_CHAR(JOINING,'DAY') FROM EMP;
SELECT TO_CHAR(JOINING,'DAY') AS RESULT FROM EMP;

SELECT JOINING FROM EMP;


SELECT * FROM EMP WHERE TO_CHAR(JOINING,'MONTH')=TO_CHAR(SYSDATE,'MONTH');

SELECT * FROM EMP WHERE JOINING>=SYSDATE-30;

SELECT * FROM EMP WHERE UPPER(TO_CHAR(JOINING,'DAY'))='MONDAY';

SELECT * FROM EMP WHERE TO_CHAR(JOINING, 'FMDAY', 'NLS_DATE_LANGUAGE=ENGLISH') = 'MONDAY';

