CREATE TABLE DEPT(
    DEPTNO INT CONSTRAINT DPK PRIMARY KEY,
    DNAME VARCHAR(30) CONSTRAINT DEPNAME CHECK(DNAME IN ('ACC','COMP','ELECT'))
    );

CREATE TABLE EMP(
    EMPNO INT CONSTRAINT EPK PRIMARY KEY,
    ENAME VARCHAR(30) CONSTRAINT UEMP UNIQUE,
    JOB VARCHAR(10) CONSTRAINT EJOB CHECK(JOB IN ('PROF','AP','LECT')),
    SAL INT CONSTRAINT ESAL NOT NULL,
    DEPTNO INT,
    MGRNO INT,
    CONSTRAINT DFK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO) ON DELETE CASCADE
);

CREATE TABLE SALES(
    SNO INT CONSTRAINT SPK PRIMARY KEY,
    SNAME VARCHAR(50),
    CITY VARCHAR(50)
    );

CREATE TABLE PART(
    P_NO INT CONSTRAINT PPK PRIMARY KEY,
    PNAME VARCHAR(50),
    COLOR VARCHAR(50)
    );

CREATE TABLE PROJECT(
    JNO INT CONSTRAINT JPK PRIMARY KEY,
    JNAME VARCHAR(50),
    CITY VARCHAR(50)
    );

CREATE TABLE SPJ(
    SNO INT,
    P_NO INT,
    JNO INT,
    QTY INT,
    CONSTRAINT SPJPK PRIMARY KEY(SNO,P_NO,JNO),
    CONSTRAINT SFK FOREIGN KEY(SNO) REFERENCES SALES(SNO),
    CONSTRAINT PFK FOREIGN KEY(P_NO) REFERENCES PART(P_NO),
    CONSTRAINT JFK FOREIGN KEY(JNO) REFERENCES PROJECT(JNO)
    );

INSERT INTO DEPT VALUES (100,'ACC');
INSERT INTO DEPT VALUES (101,'COMP');
INSERT INTO DEPT VALUES (102,'ELECT');

INSERT INTO EMP VALUES (100,'BBB','LECT',2800,101,122);
INSERT INTO EMP VALUES (112,'RAVI','AP',2500,100,100);
INSERT INTO EMP VALUES (122,'AAA','PROF',5000,102,112);
INSERT INTO EMP VALUES (114,'CCC','LECT',3002,100,112);
INSERT INTO EMP VALUES (111,'DDD','PROF',4100,101,114);

-- ALTER TABLE EMP ADD CONSTRAINT MFK FOREIGN KEY(MGRNO) REFERENCES EMP(EMPNO) ON DELETE CASCADE;
ALTER TABLE EMP ADD CONSTRAINT MFK FOREIGN KEY(MGRNO) REFERENCES EMP(EMPNO) ON DELETE SET NULL;

SELECT * FROM DEPT;
SELECT * FROM EMP;

DESC EMP;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPT';
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP DROP CONSTRAINT ESAL;

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP DROP CONSTRAINT UEMP;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP DROP CONSTRAINT DFK;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP ADD CONSTRAINT DFK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE DEPT DROP CONSTRAINT DEPNAME;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP ADD COMM INT DEFAULT 0;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP';

ALTER TABLE EMP MODIFY COMM DEFAULT NULL;

CREATE TABLE COPY AS SELECT * FROM EMP;
SELECT * FROM COPY;

CREATE TABLE DIFF AS 
SELECT EMPNO AS ENO, ENAME AS ENPNAME, JOB AS JOBB,SAL AS SALARY, DEPTNO AS DNO,MGRNO AS MGNO
FROM EMP;
SELECT * FROM DIFF;

CREATE TABLE DIFFALSO AS 
SELECT EMPNO AS ENO, ENAME AS ENPNAME, JOB AS JOBB,SAL AS SALARY, DEPTNO AS DNO,MGRNO AS MNO
FROM EMP WHERE 1=0;
SELECT * FROM DIFFALSO;

UPDATE EMP SET ENAME='QQQ',JOB='AP' WHERE EMPNO=100;
SELECT * FROM EMP;

DELETE FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='COMP');
SELECT * FROM EMP;

DELETE FROM DEPT WHERE DEPTNO=101;
UPDATE EMP SET DEPTNO=NULL WHERE DEPTNO=101;
SELECT * FROM EMP;

DELETE FROM EMP WHERE DEPTNO=102;
DELETE FROM DEPT WHERE DEPTNO=102;

SELECT * FROM DEPT;
SELECT * FROM EMP;

DELETE FROM EMP WHERE EMPNO=111;
UPDATE EMP SET MGRNO=NULL WHERE MGRNO=111;
SELECT * FROM EMP;

DELETE FROM EMP WHERE EMPNO=112;
UPDATE EMP SET MGRNO=NULL WHERE MGRNO=112;
SELECT * FROM EMP;

DROP TABLE COPY;
DROP TABLE DIFF;