SELECT * FROM DUAL;
CREATE TABLE EMPLOYEE(ENO INT,ENAME CHAR(100),JOB CHAR(20),SALARY FLOAT,COMMISION FLOAT,DEPTNO INT);

INSERT INTO EMPLOYEE VALUES(420,'GOORAV','DEV',4000,100,10);
INSERT INTO EMPLOYEE VALUES(111,'MUNNA','WORKER',2100,1200,10);
INSERT INTO EMPLOYEE VALUES(145,'KUNG PAO','DOCTOR',2999,8000,20);
INSERT INTO EMPLOYEE VALUES(222,'LIHIJU','MISTRI',1000,NULL,25);
INSERT INTO EMPLOYEE VALUES(745,'VBISES','WEB DEV',3000,NULL,30);
INSERT INTO EMPLOYEE VALUES(69,'SAYAK','KALA JADOO',500,500,30);

SELECT ENO,ENAME FROM EMPLOYEE WHERE DEPTNO=10;

SELECT ENAME FROM EMPLOYEE WHERE SALARY>2000;

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 2000 AND 3000;

SELECT * FROM EMPLOYEE WHERE DEPTNO IN (10,20,30);

SELECT ENAME FROM EMPLOYEE WHERE COMMISION IS NULL;

SELECT DEPTNO, SALARY FROM EMPLOYEE ORDER BY DEPTNO ASC, SALARY DESC;

SELECT ENAME FROM EMPLOYEE WHERE UPPER(ENAME) LIKE '%A%A%';

SELECT ENAME FROM EMPLOYEE WHERE UPPER(ENAME) LIKE '_B%';

SELECT ENAME FROM EMPLOYEE WHERE UPPER(ENAME) LIKE '%A' OR UPPER(ENAME) LIKE 'A%';

SELECT MAX(SALARY),MIN(SALARY),AVG(SALARY) FROM EMPLOYEE WHERE DEPTNO=10;

SELECT COUNT(DISTINCT ENO) FROM EMPLOYEE WHERE DEPTNO=20;

SELECT SUM(SALARY) FROM EMPLOYEE;

